### ISSUE TITLE
Program MediaTester.exe fails to start

### ISSUE THREAD

**Issue by Ricky-Tigg** [dkrahmer/MediaTester#14]
**OS:** Windows | **edition:** 11; **version:** 21H2. **MediaTester.exe version:** 0.4.1.0.

Hello. Attempts to execute this program invariably fail, producing the application error code _0xc0000135_.

**Comment by dkrahmer** [comment]
I found several articles stating that Microsoft's KB5013943 May 2022 update is causing this issue for many .Net applications. Some suggest reinstalling .Net Frameworks to resolve the issue. The following article has more information. Can you try the suggested fix then reply back with the results?

https://www.windowslatest.com/2022/05/11/kb5013943-may-2022-update-is-crashing-apps-on-windows-11/

More results: https://www.google.com/search?q=windows+11+0xc0000135

**Comment by Ricky-Tigg** [comment]
_Initial state_:

![Windows_features](https://user-images.githubusercontent.com/26058215/169071209-586920c6-6dfe-4317-bc27-ffe949b9d5fc.png)

I made by confusion a variant of the suggested methodology. Here it is:
1. **Disable** .NET Framework 4.8; click OK;
2. **Enable** .NET Framework 4.8 and 3.5; click OK;
3. **Disable** .NET Framework 3.5; click OK;
4. Reboot system.

This leads to a successful start.

**Comment by dkrahmer** [comment]
Awesome! I am glad you got it working.
Thank you for the replying back with detailed steps to resolve. This information should be helpful to others as well.
