### ISSUE TITLE
Media test failed, and then cleared all the data from the drive.

### ISSUE THREAD

**Issue by nuttapillar** [dkrahmer/MediaTester#18]
I had spent about 5 days waiting for this program to test a 14tb drive. It filled up, and then spent a few days testing, it was nearly done. And then it showed a failure, and I couldn't do a quick re-test, as all the written data had disappeared!

**Comment by dkrahmer** [comment]
Did you have the option enabled to remove temp data upon completion?

**Comment by nuttapillar** [comment]
Damn, I have clicked default options, so I'm not sure. I think I have reset it to default, so it's hard for me to tell, but perhaps i had made that mistake. Anyway, the test was nearly done, and my computer froze up for a bit due to some other issues, so would a frozen pc cause this test to fail? I'm thinking of just assuming the drive is fine, and not bothering to start the test again. It was looking fine until my computer froze. it was still several hours away from finishing, so I'm not sure if its supposed to stop like that, or go right to the end.

**Comment by dkrahmer** [comment]
When MediaTester gets to the end it outputs a report summary then waits for another task.
