### ISSUE TITLE
Fody.WeavingTask was not given a value for the required parameter SolutionDir

### ISSUE THREAD

**Issue by EvertKuijpers** [dkrahmer/MediaTester#5]
I unzipped the latest MediaTester-master.zip and loaded MediaTester.sln in Visual Studio 2019.
I did a rebuild of the solution and a build afterwards. I got the error message '
The "Fody.WeavingTask" task was not given a value for the required parameter "SolutionDir".
' twice, at line 53 of Fody.targets, both on project MediaTester and on project MediaTesterCli.
Can you help me find out if I am doing something wrong?

**Comment by fabianoriccardi** [comment]
A bit late, but I had solved upgrading the Fody packages.

**Comment by dkrahmer** [comment]
MediaTester was developed in VS2017. There may be some incompatibilities with other environments. This issue should be resolved with pending upgrades.

**Comment by fabianoriccardi** [comment]
> MediaTester was developed in VS2017. There may be some incompatibilities with other environments. This issue should be resolved with pending upgrades.

It should be solved, I had tested it with VS2022. If it doesn't work immediately, check if nuget packages are properly installed, and then restart visual studio.
